/**
 * Copyright © 2026 Nexify CRM Systems AS. All rights reserved.
 * Org.nr: 936300278 — Proprietary and confidential.
 * Unauthorized copying, distribution, or use is strictly prohibited.
 */

/**
 * telegram.duplicatePost.
 *
 * The previous version asserted `expect(result).toBeDefined()` and put the
 * "should throw" cases inside a bare try/catch with the assertion only in the
 * catch — so a procedure that quietly succeeded passed the test that existed to
 * prove it refuses. It also failed outright, because its db mock was built from
 * `vi.fn().mockReturnThis()` at module scope and the suite runs with
 * `mockReset: true`.
 *
 * What actually matters about duplicatePost is what the copy carries: the
 * original's brand (PR #79 — never the currently-active brand), the caller's own
 * userId, and fresh timestamps.
 */

import { describe, it, expect, beforeEach, vi } from "vitest";
import { createFakeDb, queryOf, type FakeDb } from "./testing/fakeDb";
import { mkCtx } from "./testing/ctx";

let fake: FakeDb;

// Plain function, not a spy: `mockReset: true` strips spy implementations.
// Spread the real module: `caller()` imports the WHOLE router graph, and other
// routers (e.g. paymentRouter) import named db helpers eagerly. A factory that
// exported only getDb left those bindings undefined for the whole file — fine
// until someone adds a case that touches one, then an unreadable
// "x is not a function". Only getDb is overridden.
vi.mock("./db", async (importOriginal) => ({
  ...(await importOriginal<typeof import("./db")>()),
  getDb: async () => fake.db,
}));

const ORIGINAL = {
  id: 1,
  userId: 1,
  brandId: 7,
  platform: "linkedin",
  tone: "professional",
  rawInput: "Test idea",
  generatedContent: "Test content generated by AI",
  tags: null,
  createdAt: new Date("2020-01-01T00:00:00Z"),
  updatedAt: new Date("2020-01-01T00:00:00Z"),
};

async function caller(userId = 1) {
  const { appRouter } = await import("./routers");
  return appRouter.createCaller(mkCtx(userId));
}

describe("telegram.duplicatePost", () => {
  beforeEach(() => {
    fake = createFakeDb({ rows: { posts: [ORIGINAL] }, returningId: { posts: [{ id: 2 }] } });
  });

  it("returns the new id and the copied content", async () => {
    const result = await (await caller()).telegram.duplicatePost({ postId: 1 });
    expect(result).toEqual({
      success: true,
      newPostId: 2,
      content: "Test content generated by AI",
    });
  });

  it("looks the original up scoped to the caller, not by id alone", async () => {
    // Distinct userId and postId, so the two bindings cannot be confused for
    // each other — with both set to 1, `eq(userId, 1)` alone would pass.
    fake = createFakeDb({ rows: { posts: [ORIGINAL] }, returningId: { posts: [{ id: 2 }] } });
    await (await caller(42)).telegram.duplicatePost({ postId: 5 });

    const read = fake.onlyOp("select", "posts");
    const { sql, params } = queryOf(read.where);
    expect(sql).toContain("user_id");
    expect(sql).toContain("`id`");
    expect(params).toEqual(expect.arrayContaining([5, 42]));
    expect(read.limit).toBe(1);
  });

  it("gives the copy the ORIGINAL's brand, never the active one", async () => {
    // PR #79: a duplicate that adopted the active brand is how a Ballong post
    // ends up publishable through Penna's channel.
    const insert = (await dup()).onlyOp("insert", "posts");
    expect((insert.values as { brandId: number }).brandId).toBe(7);
  });

  it("keeps an unowned original unowned rather than inventing a brand", async () => {
    fake = createFakeDb({
      rows: { posts: [{ ...ORIGINAL, brandId: null }] },
      returningId: { posts: [{ id: 2 }] },
    });
    const insert = (await dup()).onlyOp("insert", "posts");
    expect((insert.values as { brandId: number | null }).brandId).toBeNull();
  });

  it("copies content and platform verbatim but stamps fresh timestamps", async () => {
    const insert = (await dup()).onlyOp("insert", "posts");
    const v = insert.values as Record<string, unknown>;

    expect(v.platform).toBe("linkedin");
    expect(v.tone).toBe("professional");
    expect(v.rawInput).toBe("Test idea");
    expect(v.generatedContent).toBe("Test content generated by AI");
    expect(v.userId).toBe(1);

    // Not the original's 2020 timestamps — the copy is new.
    expect((v.createdAt as Date).getTime()).toBeGreaterThan(ORIGINAL.createdAt.getTime());
    expect((v.updatedAt as Date).getTime()).toBeGreaterThan(ORIGINAL.updatedAt.getTime());
  });

  it("refuses when the scoped lookup finds nothing, and writes nothing", async () => {
    // This covers both "no such post" and "not yours" — the scoped SELECT above
    // is what distinguishes them, and it is asserted in its own test. Do not read
    // this as a cross-tenant check on its own: the fake does not apply WHERE.
    fake = createFakeDb({ rows: { posts: [] } });
    await expect((await caller()).telegram.duplicatePost({ postId: 999 })).rejects.toThrow(
      /Post not found/,
    );
    expect(fake.opsOf("insert")).toHaveLength(0);
  });

  async function dup(userId = 1) {
    await (await caller(userId)).telegram.duplicatePost({ postId: 1 });
    return fake;
  }
});
